### PR TITLE
Regenerate study plan

### LINKED ISSUE #34: Add "Re-Generate" calendar feature to the model
Add "Re-Generate" calendar feature to the model.

This feature needs to be implemented somehow, to allow users to regenerate study period and remember the progress of the last one

### LINKED ISSUE #57: Add tests for regenerate feature
Need to add some tests regaurding the regenerate feature.

### LINKED ISSUE #62: Some study sessions are not deleted
Some study sessions are not deleted after a second generation, eventhough they are needed to be deleted beause they ovelap with some user events.

This is happening always when the start time of the study session equals the start time of any user event.
Moreover, it is happening rarely in other cases.

### PR DESCRIPTION
**Pull request by itayf9**
This PR implements the "regenerate" feature.

- Refactor the `scanUserEvents` method to be able to use it both in `/scan` (regular generate) and `/re-generate` (regenerate).
- Added two "wrapper" methods, one for each endpoint, in order to make different logic for each of the features.
- Added `GeneralErrorInEngineException` which can be used for delivering information as in `ResponseToController`, from methods where the rerturn value is different.
- Fixed existing tests to work properly after the refactor was made.
- Added a new test for the regenerate feature.
- Rename `scanUserEvents` to `scanUserEventsAndGeneratePlan`
- close #34 
- close #62 
- close #57

### CODE REVIEW

**Comment by itayf9** [comment]
### Current issues:

- The proportions between the various courses in the regenerate is incorrect.
- Need to write some tests to the regenerate feature #57 .
- The #62 issue is also relevant but not exclusivly.

**Review by Danielsio — COMMENTED** [review]
Good Work so far, i will start working on those bugs you spoke

**Review by Danielsio — APPROVED** [review]

**Comment by itayf9** [comment]
The last commit closes #62

**Review by oshriFadlon1 — APPROVED** [review]

**Comment by itayf9** [comment]
Those commits close #57 and fix the bug of the proportions between the various courses in the regenerate which was incorrect.

**Pull request merged**
